### ISSUE TITLE
关于xml转化html的问题

### ISSUE THREAD

**Issue by BangdongChen** [wangwen-whu/WTW-Dataset#2]
你好，数据集里面有些图片是旋转了90度的（例如：20200211174532996748-0.jpg）．这部分数据怎么转化成html呢？

**Comment by wangwen-whu** [comment]
数据是按照原图进行的标注，因此gt与图片一致，不区分是否旋转。可认为是倾斜的特殊情况。
The data are marked according to the images, GT are associated with the picture, whether to rotate or not is not distinguished.

**Comment by BangdongChen** [comment]
@wangwen-whu 好的，那请问你们什么时候会将　**xmltohtml.py**　这个转换代码开源？谢谢

**Comment by wangwen-whu** [comment]
> @wangwen-whu 好的，那请问你们什么时候会将　**xmltohtml.py**　这个转换代码开源？谢谢

Hi, we will update it soon~
