### ISSUE TITLE
About the results in the paper

### ISSUE THREAD

**Issue by BangdongChen** [wangwen-whu/WTW-Dataset#3]
Hello, I have some questions about the results of the test set in the paper. In the paper, you divide the test set into 7 different sub-categories, which contain 'Irregular tables'. However, in Table 4, there is no result of "Irregular tables", instead there is a result of "Simple tables" which has not been mentioned before. How do you understand this?

**Comment by wangwen-whu** [comment]
> Hello, "Irregular tables" here is a description global representation, means the table is not common, with  spaning multiple rows and columns. The data classification test is subject to the result in Table 4.  And due to the overlap of data style( one table may have two or above features), the classification of data categories cannot be very accurate.
