### ISSUE TITLE
About the wireless of ICDAR 2019

### ISSUE THREAD

**Issue by yongshuaihuang** [wangwen-whu/WTW-Dataset#5]
Hi， thanks for your Excellent work! 
I have a question about the wireless table of icdar2019. In your paper,  you said 'For lacking wireless table in WTW, we finetune the Cycle-CenterNet on the ICDAR2019 trainingset and test on ICDAR 2019 Track B2 dataset', But, icdar2019 TrackB.2 ‘Morden Dataset’  only has 100 test sets. TrackB,1 only has 'Historical Datasets'.
Which wireless dataset  did you use in your paper?

**Comment by wangwen-whu** [comment]
> Hi， thanks for your Excellent work!
> I have a question about the wireless table of icdar2019. In your paper, you said 'For lacking wireless table in WTW, we finetune the Cycle-CenterNet on the ICDAR2019 trainingset and test on ICDAR 2019 Track B2 dataset', But, icdar2019 TrackB.2 ‘Morden Dataset’ only has 100 test sets. TrackB,1 only has 'Historical Datasets'.
> Which wireless dataset did you use in your paper?

Hi，In ICDAR 2019, we use the table structure recognition gt ,  some ‘Morden Dataset’ without these kind of gt, and the test set is 'Historical Datasets' about 750(maybe) images.

**Comment by yongshuaihuang** [comment]
你们论文中的表6的结果，是指在ICDAR2019 TrackB2 Modern 100张上面的结果吧？

**Comment by yongshuaihuang** [comment]
抱歉，还是没清楚。
1. 你们论文表6的结果，是在icdar2019 trackB2 modern 数据集（100张）上的结果吧？
2. 我想问的是，你们finetune用的icdar2019 无线表， 是哪个数据集呢？

感谢回复

**Comment by wangwen-whu** [comment]
> 抱歉，还是没清楚。
> 
> 1. 你们论文表6的结果，是在icdar2019 trackB2 modern 数据集（100张）上的结果吧？
> 2. 我想问的是，你们finetune用的icdar2019 无线表， 是哪个数据集呢？
> 
> 感谢回复

你好，是这样的，为了和其他模型正常对比，icdar2019的数据我们没有进行筛选，对应于表格结构识别这个任务，icdar2019的训练集是什么我们就用了什么，测试集是什么我们就用了什么，我个人记得是只有古籍数据有表格结构识别的测试gt的，现代数据是对应其他任务的，您可以下载全部的icdar2019数据按照不同的任务gt去划分他的数据构成。

希望可以解答您的疑问~

**Comment by yongshuaihuang** [comment]
古籍是有训练（600张图）和测试（150张图）的，现代只有测试（100张图）。
你们论文中的表6，TabStruct-Net的结果，是在古籍上的（论文中说的是 cDtar-archival），据我理解，您论文中的结果，也应该是在古籍，也就是 TrackB1。 而不是 Mordern(TrackB2)

**Comment by wangwen-whu** [comment]
> 古籍是有训练（600张图）和测试（150张图）的，现代只有测试（100张图）。
> 你们论文中的表6，TabStruct-Net的结果，是在古籍上的（论文中说的是 cDtar-archival），据我理解，您论文中的结果，也应该是在古籍，也就是 TrackB1。 而不是 Mordern(TrackB2)

嗯对是的，我们只在有表格结构识别的gt的训练集和测试集进行了训练和测试，我记得是都是古籍图，至于具体是track1 还是b2，我当时下载的文件夹是这样标注，可能导致有点出入

**Comment by yongshuaihuang** [comment]
嗯，所以你们论文中表6， Icdar-20119 TrackB2(Modern) 有误，应该是 Icdar-20119 TrackB1(archival)
